#!/bin/bash

_APT_UPDATED=false
MEPH2_BRANCH="lp:~smoser/maas/maas-ephemerals-v2"
SSTREAM_BRANCH="lp:simplestreams"
CROSS_DEPS=( qemu-user-static u-boot-tools )
MEPH2_D=""

error() { echo "$@" 1>&2; }
fail() { [ $# -eq 0 ] || error "$@"; exit 2; }

rel="$(lsb_release -sc)"
if [[ "$rel" < trusty ]]; then
    error "# WARN: building not supported prior to trusty" 1>&2
    error "# WARN:  but meph2-util (index operations) supported" 1>&2
    DEPS=(
        bzr
        python3
    )
    distro_simplestreams=false
    meph2_only=true
else
    DEPS=(
        bzr
        cloud-image-utils      # for mount-image-callback
        python3-distro-info
        python3-requests
        python3-simplestreams
        python3-yaml
        simplestreams
        zerofree
    )
    distro_simplestreams=true
    meph2_only=false
fi

me=$(readlink -f "$0")
myd=$(dirname "$me")
if [ -f "$myd/bin/meph2-cloudimg-sync" ]; then
    MEPH2_D="$myd"
elif [ -f "$PWD/maas-ephemerals-v2/bin/meph2-cloudimg-sync" ]; then
    MEPH2_D="$PWD/maas-ephemerals-v2"
fi


apt_get() {
    local ret=""
    if [ "$1" != "update" ] && ! $_APT_UPDATED; then
        error "updating apt"
        apt_get update >/dev/null || {
            ret=$?;
            error "failed to update apt [$ret]";
            return $ret;
        }
        _APT_UPDATED=true
    fi
    sudo DEBIAN_FRONTEND=noninteractive apt-get --quiet \
        --assume-yes "$@" </dev/null
}

filter_installed_packages() {
    # write to stdout, a list of packages not installed locally
    local fmt='${Package} ${Version}\n'
    LC_ALL=C dpkg-query --show "--showformat=${fmt}" "$@" 2>&1 | awk '
        $0 ~ /[Nn]o packages/ {
            sub("[.]$","",$NF);
            pkgs[n]=$NF;
            n=n+1;
        }
        $2 == "" {
                pkgs[n]=$1;
                n=n+1;
        };
        END { for(p in pkgs) {printf("%s ",pkgs[p])}; printf("\n"); }' n=0
}

apt_install() {
    local needed
    needed=$(filter_installed_packages "$@")
    [ -z "$needed" ] && return 0
    error "installing: $needed"
    apt_get install "$@"
}

arch=$(dpkg --print-architecture)
deps=( "${DEPS[@]}" )
if [ "$arch" = "amd64" ] && ! $meph2_only; then
    deps=( "${deps[@]}" "${CROSS_DEPS[@]}" )
fi

apt_install "${deps[@]}"

if [ -z "$MEPH2_D" ]; then
    error "getting $MEPH2_BRANCH to $PWD/maas-ephemerals-v2"
    bzr branch "$MEPH2_BRANCH" maas-ephemerals-v2 ||
        fail "failed branch $MEPH2_BRANCH"
    MEPH2_D="$PWD/maas-ephemerals-v2"
fi

if ! $distro_simplestreams; then
    sstream_d="$MEPH2_D/simplestreams"
    if [ ! -d "$sstream_d" ] &&
        ! python -c 'import simplestreams' 2>/dev/null; then
        error "getting $STREAM_BRANCH to $sstream_d. you will need PYTHONPATH=$sstream_d."
        bzr branch "$SSTREAM_BRANCH" "$MEPH2_D/simplestreams" ||
            fail "failed to get $SSTREAM_BRANCH"
    fi
fi

# vi: ts=4 expandtab
